// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpiderX.Proxy;

namespace SpiderX.Proxy.Migrations
{
    [DbContext(typeof(SqlServerProxyDbContext))]
    [Migration("20181122171133_InitProxyEntity")]
    partial class InitProxyEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpiderX.Proxy.SpiderProxyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("AnonymityDegree");

                    b.Property<byte>("Category");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.Property<string>("Location");

                    b.Property<int>("Port");

                    b.Property<int>("ResponseMilliseconds");

                    b.Property<string>("Source");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port")
                        .IsUnique();

                    b.ToTable("ProxyEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
